import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, Download, ExternalLink, FolderSearch, HardDrive, LoaderCircle, MoreHorizontal, Play, RefreshCw, Search, ShieldCheck, Trash2, XCircle } from 'lucide-react'
import { api, del, formatBytes, post } from '../lib/api'
import { Badge, Meter, Modal } from '../components/ui'
import type { EngineStatus, Model } from '../types'

export default function Models({engine,models,refresh,toast}:{engine:EngineStatus;models:Model[];refresh:()=>void;toast:(s:string,b?:boolean)=>void}) {
  const [tab,setTab]=useState<'library'|'discover'>('library'),[query,setQuery]=useState(''),[catalog,setCatalog]=useState<any[]>([]),[searching,setSearching]=useState(false),[job,setJob]=useState<any>(null),[confirm,setConfirm]=useState<Model|null>(null),[advanced,setAdvanced]=useState<Model|null>(null)
  useEffect(()=>{api<any>('/api/models/catalog').then(v=>setCatalog(v.items))},[])
  useEffect(()=>{if(!job||!['queued','running','cancelling'].includes(job.state))return;const id=setInterval(()=>api<any>(`/api/jobs/${job.id}`).then(v=>{setJob(v);if(v.state==='completed'){toast('Model download complete');refresh()}}),1000);return()=>clearInterval(id)},[job,refresh,toast])
  const load=async(model:Model,options={})=>{try{await post(`/api/models/${encodeURIComponent(model.id)}/load`,{options,switch:['ready','external'].includes(engine.state)});toast(`Loading ${model.name}`);setAdvanced(null);refresh()}catch(e:any){toast(e.message,true)}}
  const remove=async(model:Model)=>{try{await del(`/api/models/${encodeURIComponent(model.id)}${model.status==='running'?'?unload=true':''}`);toast(`${model.name} deleted`);setConfirm(null);refresh()}catch(e:any){toast(e.message,true)}}
  const discover=async()=>{setSearching(true);try{const v=await api<any>(`/api/models/search?query=${encodeURIComponent(query)}`);setCatalog(v.items)}catch(e:any){toast(e.message,true)}finally{setSearching(false)}}
  const download=async(repo:string)=>{try{const v=await post<any>('/api/models/download',{repoId:repo});setJob(v);toast('Download started')}catch(e:any){toast(e.message,true)}}
  return <div className="page models-page"><div className="page-heading"><div><div className="eyebrow">CHECKPOINTS / LOCAL STORAGE</div><h1>Models</h1><p>Discover known-good checkpoints, then download and launch them in place.</p></div><button className="secondary" onClick={async()=>{await post('/api/models/rescan');refresh();toast('Library rescanned')}}><RefreshCw size={16}/>Rescan</button></div><div className="tabs"><button className={tab==='library'?'active':''} onClick={()=>setTab('library')}>Library <em>{models.length}</em></button><button className={tab==='discover'?'active':''} onClick={()=>setTab('discover')}>Discover</button></div>
    {job&&['queued','running','cancelling','failed'].includes(job.state)&&<section className="download-job"><div><span className="download-icon"><Download/></span><div><small>{job.progress?.file||job.payload?.repoId}</small><strong>{job.state==='failed'?job.error:`Downloading ${job.payload?.repoId}`}</strong></div></div><div className="job-progress"><span>{formatBytes(job.progress?.downloadedBytes)} / {formatBytes(job.progress?.totalBytes)}<b>{job.progress?.percent??0}%</b></span><Meter value={job.progress?.percent||2}/><small>{job.progress?.speedBytesPerSecond?`${formatBytes(job.progress.speedBytesPerSecond)}/s`:job.state}</small></div>{['queued','running'].includes(job.state)?<button className="secondary compact" onClick={()=>post(`/api/jobs/${job.id}/cancel`).then(()=>toast('Cancelling download'))}>Cancel</button>:<button className="primary compact" onClick={()=>download(job.payload.repoId)}>Retry</button>}</section>}
    {tab==='library'?<div className="model-list">{models.length===0?<div className="model-empty"><FolderSearch/><h3>No complete checkpoints found</h3><p>Place compatible models in the configured models directory or discover one here.</p><button className="primary" onClick={()=>setTab('discover')}>Discover models</button></div>:models.map(model=><article className="model-row" key={model.id}><div className="model-glyph large">{model.name.slice(0,2).toUpperCase()}</div><div className="model-name"><div><h3>{model.name}</h3>{model.compatibility==='verified'&&<ShieldCheck size={15}/>}</div><p>{model.repository||model.architecture}</p><span>{model.parameterCount||'Parameters unknown'} · {model.quantization||'Native weights'} · {formatBytes(model.sizeBytes)}</span></div><div className="model-tags"><Badge tone={model.status==='running'?'good':model.status==='failed'?'bad':'neutral'}>{model.status}</Badge><Badge tone={model.compatibility==='verified'?'accent':model.compatibility==='likely'?'warn':'neutral'}>{model.compatibility}</Badge></div><div className="model-actions"><button className="primary compact" disabled={model.status==='failed'||['starting','loading','stopping'].includes(engine.state)} onClick={()=>load(model)}><Play size={14}/>{model.status==='running'?'Running':'Load'}</button><button className="icon-button" onClick={()=>setAdvanced(model)} title="Advanced load"><MoreHorizontal/></button><button className="icon-button danger" onClick={()=>setConfirm(model)} title="Delete"><Trash2/></button></div>{model.issue&&<div className="model-issue"><XCircle size={14}/>{model.issue}</div>}</article>)}</div>:
    <><form className="catalog-search" onSubmit={e=>{e.preventDefault();discover()}}><Search/><input placeholder="Search Hugging Face repositories" value={query} onChange={e=>setQuery(e.target.value)}/><button className="primary" disabled={searching||query.length<2}>{searching?<LoaderCircle className="spin"/>:'Search'}</button></form><div className="catalog-grid">{catalog.map(item=><article className="catalog-card" key={item.repo}><header><span className="model-glyph">{item.repo.split('/').pop()?.slice(0,2).toUpperCase()}</span><Badge tone={item.compatibility==='verified'?'accent':'neutral'}>{item.compatibility}</Badge></header><h3>{item.repo.split('/').pop()}</h3><p>{item.family||item.repo.split('/')[0]}</p>{item.notes&&<small>{item.notes}</small>}<footer><a href={item.huggingFaceUrl} target="_blank" rel="noreferrer">Details <ExternalLink size={13}/></a><button className="primary compact" onClick={()=>download(item.repo)} disabled={job&&['queued','running'].includes(job.state)}><Download size={14}/>Download</button></footer></article>)}</div></>}
    {confirm&&<Modal title="Delete checkpoint?" onClose={()=>setConfirm(null)}><div className="confirm-body"><div className="warning-mark"><Trash2/></div><p><strong>{confirm.name}</strong> will be permanently removed from model storage.</p><div className="recovery"><HardDrive/> Reclaims approximately <b>{formatBytes(confirm.sizeBytes)}</b></div>{confirm.status==='running'&&<p className="warning-text">The model is running. It will be unloaded first.</p>}<footer><button className="secondary" onClick={()=>setConfirm(null)}>Keep model</button><button className="danger-button" onClick={()=>remove(confirm)}>Delete permanently</button></footer></div></Modal>}
    {advanced&&<Advanced model={advanced} onClose={()=>setAdvanced(null)} onLoad={load}/>} </div>
}

function Advanced({model,onClose,onLoad}:{model:Model;onClose:()=>void;onLoad:(m:Model,o:any)=>void}) {const [opts,setOpts]=useState<any>({gpu:'auto',memoryRatio:.9,moeBackend:'auto',maxRunningRequests:4,maxOutputTokens:32768});return <Modal title={`Load ${model.name}`} onClose={onClose}><div className="advanced-form"><p>FreeToken resolves hardware and checkpoint defaults automatically. Only override what you understand.</p><div className="field-grid"><label>GPU<input value={opts.gpu} onChange={e=>setOpts({...opts,gpu:e.target.value})}/></label><label>Memory ratio<input type="number" min="0.1" max="1" step="0.05" value={opts.memoryRatio} onChange={e=>setOpts({...opts,memoryRatio:+e.target.value})}/></label><label>MoE backend<select value={opts.moeBackend} onChange={e=>setOpts({...opts,moeBackend:e.target.value})}><option>auto</option><option>offload</option><option>cpu</option><option>hybrid</option><option>fused</option></select></label><label>Concurrent requests<input type="number" min="1" value={opts.maxRunningRequests} onChange={e=>setOpts({...opts,maxRunningRequests:+e.target.value})}/></label><label>Default output tokens<input type="number" min="1" value={opts.maxOutputTokens} onChange={e=>setOpts({...opts,maxOutputTokens:+e.target.value})}/></label></div><footer><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onLoad(model,opts)}><Play size={15}/>Load model</button></footer></div></Modal>}
