import { Activity, Cpu, Database, Gauge, MemoryStick, Thermometer } from 'lucide-react'
import { formatBytes } from '../lib/api'
import { Meter } from '../components/ui'
import type { EngineStatus, Metrics } from '../types'

export default function Performance({engine,metrics}:{engine:EngineStatus;metrics:Metrics|null}) {const gpu=metrics?.system.gpus[0],r=metrics?.runtime||{},history=metrics?.history||[];return <div className="page performance"><div className="page-heading"><div><div className="eyebrow">TELEMETRY / 2.5S SAMPLE</div><h1>Performance</h1><p>Live machine and FreeToken runtime signals. No estimated throughput.</p></div><span className="live-dot">LIVE</span></div><div className="performance-head"><article><small>DECODE THROUGHPUT</small><strong>{(r.throughput?.decode_tps||0).toFixed(1)}<em> tok/s</em></strong><span>{r.throughput?.prefill_tps||0} prefill tok/s</span></article><article><small>P95 REQUEST LATENCY</small><strong>{r.requests?.p95_ms||0}<em> ms</em></strong><span>{r.requests?.active||0} requests active</span></article><article><small>TIME TO FIRST TOKEN</small><strong>{r.requests?.ttft_mean_ms||0}<em> ms</em></strong><span>runtime mean</span></article></div><section className="chart-panel"><header><div><small>ROLLING HISTORY</small><h3>Engine & hardware pulse</h3></div><div className="legend"><span className="decode">Decode tok/s</span><span className="gpu">GPU %</span></div></header><LineChart points={history}/></section><div className="resource-grid"><Resource icon={<Cpu/>} name="CPU" value={metrics?.system.cpu.percent||0} detail={`${metrics?.system.cpu.cores||0} logical cores`}/><Resource icon={<MemoryStick/>} name="System RAM" value={metrics?.system.ram.percent||0} detail={`${formatBytes(metrics?.system.ram.usedBytes)} / ${formatBytes(metrics?.system.ram.totalBytes)}`}/><Resource icon={<Gauge/>} name="GPU compute" value={gpu?.utilization||0} detail={gpu?.name||'NVML unavailable'}/><Resource icon={<Database/>} name="GPU VRAM" value={gpu?.memoryPercent||0} detail={`${formatBytes(gpu?.memoryUsedBytes)} / ${formatBytes(gpu?.memoryTotalBytes)}`}/></div><div className="detail-panels"><section className="panel"><header><div><small>GPU DEVICE</small><h3>{gpu?.name||'Not detected'}</h3></div><Thermometer/></header><dl><div><dt>Temperature</dt><dd>{gpu?`${gpu.temperatureC}°C`:'—'}</dd></div><div><dt>Power draw</dt><dd>{gpu?`${gpu.powerWatts} W`:'—'}</dd></div><div><dt>UUID</dt><dd>{gpu?.uuid||'—'}</dd></div></dl></section><section className="panel"><header><div><small>FREETOKEN POOLS</small><h3>Runtime allocation</h3></div><Activity/></header><dl><div><dt>KV cache</dt><dd>{r.kv?`${r.kv.used_pages} / ${r.kv.total_pages} pages`:'Not active'}</dd></div><div><dt>Mamba cache</dt><dd>{r.mamba?`${r.mamba.used_slots} / ${r.mamba.total_slots} slots`:'Not used by model'}</dd></div><div><dt>Engine VRAM</dt><dd>{formatBytes(r.vram_bytes)}</dd></div></dl></section></div></div>}
function Resource({icon,name,value,detail}:{icon:any;name:string;value:number;detail:string}){return <article className="resource"><header><span>{icon}</span><small>{name}</small><b>{value.toFixed(0)}%</b></header><Meter value={value} tone={value>90?'orange':'accent'}/><p>{detail}</p></article>}
function LineChart({points}:{points:any[]}){if(points.length<2)return <div className="chart-empty">Collecting live samples…</div>;const w=900,h=220,maxT=Math.max(10,...points.map(p=>p.decodeTps||0));const path=(key:string,max:number)=>points.map((p,i)=>`${i?'L':'M'} ${(i/(points.length-1))*w} ${h-(Math.max(0,p[key]||0)/max)*(h-20)-10}`).join(' ');return <svg className="line-chart" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ee8b4a" stopOpacity=".28"/><stop offset="1" stopColor="#ee8b4a" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3,4].map(i=><line key={i} x1="0" x2={w} y1={i*h/4} y2={i*h/4}/>) }<path className="area" d={`${path('decodeTps',maxT)} L ${w} ${h} L 0 ${h} Z`}/><path className="decode-line" d={path('decodeTps',maxT)}/><path className="gpu-line" d={path('gpu',100)}/></svg>}

